name: Przykład Automatyzacji

on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout code
             uses: actions/checkout@v2
             
           - name: Set up Node.js
             uses: action/setup-node@v4
             with:
                    node-version: '20'
           - name: Install dependencies
             run: npm install

           - name: Run test
             run: npm test